spring.application.name=citrus-sync

spring.datasource.url=jdbc:postgresql://localhost:5432/citrussync
spring.datasource.username=postgres
spring.datasource.password=bloodorange

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
